version: 0.2

env:
  variables:
    REPOSITORY_REGION: "us-east-1"
    ENV: "dev"
    APP_NAME: "goapp"
    
phases:
  pre_build:
    commands:
      
  build:
    commands:
      - echo "Build and push docker images"
      - go version
      - make ci