version: 0.2

env:
  variables:
    REPOSITORY_REGION: "us-east-1"
    ENV: "dev"
    APP_NAME: "goapp"
    
phases:
  pre_build:
    commands:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.46.2
      
  build:
    commands:
      - echo "Build and push docker images"
      - go version
      - make ci
      - export TAG="${CODEBUILD_RESOLVED_SOURCE_VERSION}-${ENV}"
      - echo "Building version ${TAG}"
      - make push-ecr